[versions]
kotlin = "2.2.0"
ktor = "3.2.0"
versions = "0.52.0"
vapi4k = "1.3.0"

[libraries]
vapi4k-core = { group = "com.github.vapi4k.vapi4k", name = "vapi4k-core", version.ref = "vapi4k" }
vapi4k-dbms = { group = "com.github.vapi4k.vapi4k", name = "vapi4k-dbms", version.ref = "vapi4k" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versions" }